
# Global configuration for the stock-screener pipeline.
# Edit values here to change runtime behavior without modifying code.

# Download parameters
TickerSymbols:
  - "AAPL"
  - "MSFT"
StartDate: "2023-01-01"
EndDate: "2023-12-31"
Interval: "1d"  # e.g., 1d, 1h, 5m
