Ticker: "AAPL"
StartDate: "2020-01-01"
EndDate: "2024-12-31"
Interval: "1d"
CacheDir: "Cache"
Tickers:
  - "AAPL"
  - "MSFT"
  - "RUN"
  - "SSL"
  - "DAR"
  - "BHC"
  - "ORCL"
  - "FRO"
  - "RH"
  - "CF"
  - "CIVI"
  - "APGE"
  - "VEON"
  - "ACHR"
  - "DAVE"
  - "APLD"
  - "NEGG"
  - "VKTX"
  - "VFC"
  - "TLX"
  - "WRD"
  - "CPAY"
CompositeMetrics:
  - "CAGR"
  - "Volatility"
  - "MaxDrawdown"
  - "SharpeRatio"
  - "SortinoRatio"

TopN: 50
Alpha: 0.4
